# Generated by Django 5.0.6 on 2024-05-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_lab_tech',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_standard_user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('lab_tech', 'Lab Technician'), ('standard', 'Standard User')], default='standard', max_length=10),
        ),
    ]
