# Generated by Django 5.0.6 on 2024-05-17 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_remove_customuser_is_lab_tech_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labequipment',
            name='available_quantity',
        ),
    ]
