# Generated by Django 5.0.6 on 2024-05-18 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_remove_labequipment_available_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
